#pragma once

/*******************************************************************************

In a ClusterGraph, each vertex represents a valid cluster from variant clustering.
Edges are generated by following the reads - if a read has markers in two 
different clusters, there is a connection between those clusters.

This graph allows visualization and analysis of how clusters are ordered
along reads, similar to how AnchorGraph shows anchor connectivity.

*******************************************************************************/

// Dinara.
#include "ReadId.hpp"
#include "dinaraTypes.hpp"

// Boost libraries.
#include <boost/graph/adjacency_list.hpp>

// Standard library.
#include "array.hpp"
#include "iosfwd.hpp"
#include <map>
#include "memory.hpp"
#include "string.hpp"
#include "utility.hpp"
#include "vector.hpp"

namespace dinara {

    class Assembler;

    class ClusterGraphVertex;
    class ClusterGraphEdge;
    class ClusterGraph;
    using ClusterGraphBaseClass = boost::adjacency_list<
        boost::listS,
        boost::listS,
        boost::bidirectionalS,
        ClusterGraphVertex,
        ClusterGraphEdge>;

    class ClusterGraphDisplayOptions;

}



// Class to control Graphviz output of ClusterGraph.
class dinara::ClusterGraphDisplayOptions {
public:
    // Graph size in pixels.
    uint64_t sizePixels = 800;
    
    // Edge length scaling factor for layout (larger = more spread out graph).
    // This controls the 'K' parameter in sfdp.
    double edgeLengthScale = 1.0;
    
    // Timeout in seconds for Graphviz layout computation.
    double timeout = 30.0;
    
    // Vertex options.
    double vertexSize = 1.0;
    bool vertexSizeByCoverage = false;
    bool vertexLabels = false;
    std::string vertexColoring = "byAlleleCount";  // "black", "byAlleleCount"
    
    // Edge options.
    double edgeThickness = 1.0;
    bool edgeLabels = false;
    std::string edgeColoring = "byCoverage";  // "black", "byCoverage"
    double arrowSize = 0.5;
    
    // Thresholds for coloring by coverage.
    uint64_t lowCoverage = 1;
    uint64_t highCoverage = 10;

    ClusterGraphDisplayOptions() = default;
    
    // Construct from HTTP request.
    ClusterGraphDisplayOptions(const std::vector<std::string>& request);
    
    // Write the form.
    void writeForm(std::ostream& html) const;
};



class dinara::ClusterGraphVertex {
public:
    // The global cluster ID (representative index in disjoint sets).
    uint64_t clusterId;
    
    // The local cluster ID (index into the clusterIds vector).
    uint64_t localClusterId;
    
    // Coverage: number of reads/position pairs in this cluster.
    uint64_t coverage = 0;
    
    // Number of alleles with sufficient coverage.
    uint64_t alleleCount = 0;
    
    // Strand balance: fraction of reads on strand 0 (0.0 to 1.0).
    // 0.5 means balanced, 0.0 means all strand 1, 1.0 means all strand 0.
    double strand0Fraction = 0.5;
    
    // RC partner cluster ID (if found). Max value means no partner found.
    uint64_t rcPartnerClusterId = std::numeric_limits<uint64_t>::max();

    ClusterGraphVertex() : clusterId(0), localClusterId(0) {}
    ClusterGraphVertex(uint64_t clusterId, uint64_t localClusterId) : 
        clusterId(clusterId), localClusterId(localClusterId) {}
    
    bool hasRcPartner() const { 
        return rcPartnerClusterId != std::numeric_limits<uint64_t>::max(); 
    }
};



class dinara::ClusterGraphEdge {
public:
    // Coverage: number of reads that have markers in both clusters.
    // Special value: coverage = 0 with isRcPairEdge = true means RC pair edge.
    uint64_t coverage = 0;
    
    // Average position offset between the two clusters.
    // Positive means cluster1 comes after cluster0 on reads.
    // For RC pair edges, this is set to 0.
    int64_t averageOffset = 0;
    
    // True if this edge connects a cluster to its reverse-complement partner.
    bool isRcPairEdge = false;

    ClusterGraphEdge() = default;
    ClusterGraphEdge(uint64_t coverage, int64_t averageOffset) :
        coverage(coverage), averageOffset(averageOffset), isRcPairEdge(false) {}
    
    // Constructor for RC pair edges.
    static ClusterGraphEdge createRcPairEdge() {
        ClusterGraphEdge edge;
        edge.coverage = 0;
        edge.averageOffset = 0;
        edge.isRcPairEdge = true;
        return edge;
    }
};



class dinara::ClusterGraph : public ClusterGraphBaseClass {
public:

    // Default constructor for loading from binary.
    ClusterGraph() = default;

    // Create the ClusterGraph from the Assembler's variant clustering data.
    // Only includes valid clusters.
    ClusterGraph(
        const Assembler& assembler,
        uint64_t minEdgeCoverage = 0);

    // Create the ClusterGraph for a specific set of cluster IDs.
    ClusterGraph(
        const Assembler& assembler,
        const std::vector<uint64_t>& clusterIds,
        uint64_t minEdgeCoverage = 0);
    
    // Binary I/O.
    void save(const std::string& fileName) const;
    void load(const std::string& fileName);
    
    // Extract a subgraph containing only clusters within 'distance' hops from startClusterId.
    // Also filters edges by minEdgeCoverage.
    ClusterGraph extractNeighborhood(
        uint64_t startClusterId, 
        uint64_t distance,
        uint64_t minEdgeCoverage = 0) const;
    
    // Extract a subgraph containing only the specified cluster IDs.
    // Also filters edges by minEdgeCoverage.
    ClusterGraph extractSubgraph(
        const std::vector<uint64_t>& clusterIdsToInclude,
        uint64_t minEdgeCoverage = 0) const;

    // The cluster IDs of this ClusterGraph. Each of these corresponds to a vertex.
    // An index in this vector is called a local cluster id.
    std::vector<uint64_t> clusterIds;

    // Get the cluster ID of a given vertex.
    uint64_t getClusterId(vertex_descriptor v) const
    {
        const ClusterGraph& clusterGraph = *this;
        return clusterGraph[v].clusterId;
    }

    // The vertex_descriptor corresponding to each local cluster id.
    // Indexed by the local cluster id.
    std::vector<vertex_descriptor> vertexDescriptors;

    // Map from global cluster ID to vertex descriptor.
    // Only includes clusters that are in this graph.
    std::map<uint64_t, vertex_descriptor> clusterIdToVertex;

    // Add an edge between two vertices.
    void addEdge(
        vertex_descriptor v0,
        vertex_descriptor v1,
        uint64_t coverage,
        int64_t averageOffset);

    // Write the graph in Graphviz format.
    void writeGraphviz(
        const std::string& fileName,
        const ClusterGraphDisplayOptions& options) const;
    void writeGraphviz(
        std::ostream& out,
        const ClusterGraphDisplayOptions& options) const;

    // Write the graph as interactive HTML/SVG with controls.
    void writeHtml(
        std::ostream& html,
        const ClusterGraphDisplayOptions& options);

    // Write edge details to a CSV file.
    void writeEdgeDetails(const std::string& fileName) const;

    // Write vertex details to a CSV file.
    void writeVertexDetails(const std::string& fileName) const;

    // Remove edges with coverage below threshold.
    void removeWeakEdges(uint64_t minCoverage);

    // Get graph statistics.
    uint64_t vertexCount() const { return num_vertices(*this); }
    uint64_t edgeCount() const { return num_edges(*this); }
    
    // Count RC pair edges.
    uint64_t rcPairEdgeCount() const;

private:
    // Helper to build edges by following reads.
    void buildEdgesFromReads(
        const Assembler& assembler,
        uint64_t minEdgeCoverage);
    
    // Find and connect reverse-complement cluster pairs.
    // Two clusters are RC partners if they share the same reads but on opposite strands.
    void findAndConnectRcPairs(const Assembler& assembler);
    
    // Layout computation and SVG rendering.
    std::map<vertex_descriptor, std::array<double, 2>> layout;
    void computeLayout(const ClusterGraphDisplayOptions& options);
    
    // Bounding box for the layout.
    struct Box {
        double xMin = 0, xMax = 0, yMin = 0, yMax = 0;
        double xSize() const { return xMax - xMin; }
        double ySize() const { return yMax - yMin; }
        void makeSquare();
        void extend(double factor);
    };
    Box boundingBox;
    void computeLayoutBoundingBox();
    
    // SVG rendering helpers.
    void writeVertices(std::ostream& html, const ClusterGraphDisplayOptions& options) const;
    void writeEdges(std::ostream& html, const ClusterGraphDisplayOptions& options) const;
    void writeSvgControls(std::ostream& html) const;
};

