#pragma once

/*******************************************************************************

In a AnchorGraph, each vertex represents a global Anchor
(currently identified with a primary edge of the marker graph).
Edges are generated by following the reads.

*******************************************************************************/

// Dinara.
#include "mode3-Anchor.hpp"
#include "Base.hpp"
#include "MultithreadedObject.hpp"
#include "ReadId.hpp"
#include "dinaraTypes.hpp"

// Boost libraries.
#include <boost/graph/adjacency_list.hpp>

// Standard library.
#include "iosfwd.hpp"
#include "array.hpp"
#include "memory.hpp"
#include "string.hpp"
#include "utility.hpp"
#include "vector.hpp"
#include <map>

namespace dinara {
    class CompressedMarker;
    class AlignmentData;
    namespace MemoryMapped {
        template<class T> class Vector;
        template<class T, class Int> class VectorOfVectors;
    }

    namespace mode3 {

        // A connected component of the Anchor graph,
        // in which each vertex represents an Anchor.
        // Edges are created by following the reads on their journeys over Anchors.
        class AnchorGraphVertex;
        class AnchorGraphEdge;
        class AnchorGraph;
        using AnchorGraphBaseClass = boost::adjacency_list<
            boost::listS,
            boost::listS,
            boost::bidirectionalS,
            AnchorGraphVertex,
            AnchorGraphEdge>;

        class AnchorGraphDisplayOptions;
        class AnchorGraphSuperbubble;
        class AnchorGraphSuperbubbleChain;

    }
}



// Class to control Graphviz output of AnchorGraph.
class dinara::mode3::AnchorGraphDisplayOptions {
public:
    bool labels = true;
    bool tooltips = true;
    bool colorVertices = true;
    bool colorEdges = true;
    bool showNonTransitiveReductionEdges = true;

    // Thresholds for coloring by corrected Jaccard similarity J'.
    // If J' <= redJ, the edge is drawn red.
    // If J' >= greenJ, the edge is drawn green.
    // For values in between, the color is interpolated.
    double redJ;
    double greenJ;

    AnchorGraphDisplayOptions(double redJ = 0., double greenJ = 1.) :
        redJ(redJ), greenJ(greenJ) {}

    void makeCompact()
    {
        labels = false;
        tooltips = false;
        colorVertices = false;
        colorEdges = false;
    }
};



class dinara::mode3::AnchorGraphVertex {
public:
    uint64_t localAnchorId;
    AnchorGraphVertex() {}
    AnchorGraphVertex(AnchorId anchorId) = delete;

    // The reverse complement vertex.
    // Only used during strand separation.
    AnchorGraphBaseClass::vertex_descriptor vRc = AnchorGraphBaseClass::null_vertex();
};



class dinara::mode3::AnchorGraphEdge {
public:
    AnchorPairInfo info;
    uint64_t coverage;
    bool isNonTransitiveReductionEdge = false;
    AnchorGraphEdge(const AnchorPairInfo& info, uint64_t coverage) :
        info(info), coverage(coverage) {}

    // The reverse complement edge.
    // Only used during strand separation.
    AnchorGraphBaseClass::edge_descriptor eRc;
};



class dinara::mode3::AnchorGraph : public AnchorGraphBaseClass {
public:

    // Create the AnchorGraph and its vertices and edges given the AnchorIds
    // for a conneced component of the global anchor graph.
    AnchorGraph(
        const Anchors&,
        span<const AnchorId> anchorIds,
        uint64_t minEdgeCoverage,
        const MemoryMapped::Vector<AlignmentData>* alignmentData = nullptr,
        const MemoryMapped::VectorOfVectors<uint32_t, uint32_t>* alignmentTable = nullptr);

    // Create the AnchorGraph for ALL anchors (not per-component).
    // This is analogous to the Shasta2 top-level AnchorGraph creation.
    AnchorGraph(
        const Anchors&,
        uint64_t minEdgeCoverage,
        const MemoryMapped::Vector<AlignmentData>* alignmentData = nullptr,
        const MemoryMapped::VectorOfVectors<uint32_t, uint32_t>* alignmentTable = nullptr);

    // The AnchorIds of this AnchorGraph. Each of these corresponds to a vertex.
    // An index in this vector is called a local anchor id.
    span<const AnchorId> anchorIds;

    // Owned storage for anchorIds when the graph is created for all anchors.
    vector<AnchorId> ownedAnchorIds;

    // Get the AnchorId of a given vertex.
    // The vertex stores the local anchor id (index into the anchorIds vector).
    AnchorId getAnchorId(vertex_descriptor v) const
    {
        const AnchorGraph& anchorGraph = *this;
        const AnchorGraphVertex& vertex = anchorGraph[v];
        return anchorIds[vertex.localAnchorId];
    }

    // The vertex_descirptor corresponding to each local anchor id.
    // Index by the local anchor id.
    vector<vertex_descriptor> vertexDescriptors;

    // Add an edge between the vertices corresponding to given local anchor ids.
    void addEdgeFromLocalAnchorIds(
        uint64_t,
        uint64_t,
        const AnchorPairInfo&,
        uint64_t coverage);

    void writeGraphviz(
        const string& name,
        const AnchorGraphDisplayOptions&,
        const Anchors&) const;

    void writeEdgeCoverageHistogram(const string& fileName) const;
    void writeEdgeDetails(const string& fileName, const Anchors&) const;

    void localTransitiveReduction(
        uint64_t distance,
        uint64_t maxCoverage);

    // Remove edges with negative estimated offset.
    void removeNegativeOffsetEdges();

    // Remove cross-edges.
    // This removes an edge v0->v1 if the following are all true:
    // - Its coverage is at most lowCoverageThreshold.
    // - Its estimated offset is at least minOffset.
    // - v0 has at least one out-edge with coverage at least highCoverageThreshold.
    // - v1 has at least one in-edge with coverage at least highCoverageThreshold.
    void removeCrossEdges(
        uint64_t lowCoverageThreshold,
        uint64_t highCoverageThreshold,
        uint64_t minOffset,
        bool debug);

    // Remove edges for which loss = (commonCount - coverage) / commonCount > maxLoss
    void removeWeakEdges(double maxLoss, bool debug);

    // Transitive reduction.
    // Processes edges in order of increasing coverage (1 to maxEdgeCoverage).
    // For each edge, does BFS from source to target using only edges with
    // higher coverage and within maxDistance hops. If an alternate path exists,
    // the edge is flagged as isNonTransitiveReductionEdge.
    void transitiveReduction(uint64_t maxEdgeCoverage, uint64_t maxDistance);

    // Resolve phased superbubbles in the currently kept graph.
    // For each candidate source/sink pair supported by phase-deleted read conflicts,
    // keep only two linear chains (one per inferred haplotype) in the local interval.
    void resolvePhasedSuperbubbles(uint64_t maxDistance, bool debug = false);

    // Snarl decomposition using vg's IntegratedSnarlFinder (cactus graph).
    // Returns level-0 top snarls as (boundary0, boundary1) pairs of local anchor ids.
    void findSnarls(
        vector<pair<uint64_t, uint64_t>>& topSnarls) const;

    // Superbubble detection using flow-based convergence (ported from shasta2).
    // Finds superbubbles where all forward and backward paths converge.
    void findSuperbubbles(
        vector<AnchorGraphSuperbubble>& superbubbles,
        uint64_t maxDistance) const;
    void removeContainedSuperbubbles(
        vector<AnchorGraphSuperbubble>& superbubbles) const;
    void findSuperbubbleChains(
        const vector<AnchorGraphSuperbubble>& superbubbles,
        vector<AnchorGraphSuperbubbleChain>& chains) const;

private:
    bool findAlternatePath(
        edge_descriptor candidateEdge,
        uint64_t maxDistance,
        vector<edge_descriptor>& alternatePathEdges,
        bool onlyHigherCoverage) const;
    void getIntervalVertices(
        vertex_descriptor sourceVertex,
        vertex_descriptor targetVertex,
        uint64_t maxDistance,
        vector<vertex_descriptor>& intervalVertices) const;
    bool isAcyclicInterval(
        const vector<vertex_descriptor>& intervalVertices,
        vector<vertex_descriptor>& topologicalOrder) const;
    bool containsEdge(
        const vector<edge_descriptor>& edges,
        edge_descriptor edge) const;
    vector<edge_descriptor> computeBestHaplotypePathInInterval(
        vertex_descriptor sourceVertex,
        vertex_descriptor targetVertex,
        const vector<vertex_descriptor>& topologicalOrder,
        const vector<edge_descriptor>& intervalEdges,
        const std::map<vertex_descriptor, uint64_t>& vertexIndex,
        const vector<array<int64_t, 2> >& edgeHaplotypeScores,
        uint64_t haplotype,
        const vector<bool>& disallowedInternalVertex) const;
    void buildPhaseDeletedPartnerTable();
    void getSupportingOrientedReads(edge_descriptor, vector<OrientedReadId>&) const;
    bool hasPhaseDeletedConflict(
        const vector<OrientedReadId>& firstSet,
        const vector<OrientedReadId>& secondSet) const;
    bool keepCandidateEdgeByPhasing(
        edge_descriptor candidateEdge,
        const vector<edge_descriptor>& alternatePathEdges) const;
    bool transitiveReductionCanRemove(edge_descriptor, uint64_t maxDistance) const;

    const Anchors* anchorsPointer = nullptr;
    const MemoryMapped::Vector<AlignmentData>* alignmentDataPointer = nullptr;
    const MemoryMapped::VectorOfVectors<uint32_t, uint32_t>* alignmentTablePointer = nullptr;
    vector<vector<OrientedReadId> > phaseDeletedPartnersByRead;
    bool hasPhaseDeletedPartnerCache = false;

};
